[package]
name = "quickfix-rs"
version = "0.1.0"
authors = ["Arthur LE MOIGNE <arthur.lemoigne@gmail.com>"]
edition = "2018"

[build-dependencies]
quickfix-spec-generator = { path = "../quickfix-spec-generator" }
